function randNum() {
  return Math.floor((Math.random() * 100) + 1);
};

let contenttypes = [{
    id: { '$oid': '594585ddfc13ae3b14000131' },
    title: 'contenttype title 0',
    name: 'contentype name 0',
    content: 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
    dek: 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',
    random: 37,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b14000132' },
    title: 'contenttype title 1',
    name: 'contentype name 1',
    content: 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.',
    dek: 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',
    random: 48,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b14000133' },
    title: 'contenttype title 2',
    name: 'contentype name 2',
    content: 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
    dek: 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.',
    random: 51,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b14000134' },
    title: 'contenttype title 3',
    name: 'contentype name 3',
    content: 'Nulla ac enim.',
    dek: 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.',
    random: 84,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b14000135' },
    title: 'contenttype title 4',
    name: 'contentype name 4',
    content: 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.',
    dek: 'Phasellus in felis.',
    random: 24,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b14000136' },
    title: 'contenttype title 5',
    name: 'contentype name 5',
    content: 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.',
    dek: 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.',
    random: 66,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b14000137' },
    title: 'contenttype title 6',
    name: 'contentype name 6',
    content: 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.',
    dek: 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.',
    random: 36,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b14000138' },
    title: 'contenttype title 7',
    name: 'contentype name 7',
    content: 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.',
    dek: 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.',
    random: 67,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b14000139' },
    title: 'contenttype title 8',
    name: 'contentype name 8',
    content: 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.',
    dek: 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
    random: 100,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b1400013a' },
    title: 'contenttype title 9',
    name: 'contentype name 9',
    content: 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.',
    dek: 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.',
    random: 61,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b1400013b' },
    title: 'contenttype title 10',
    name: 'contentype name 10',
    content: 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.',
    dek: 'Sed accumsan felis. Ut at dolor quis odio consequat varius.',
    random: 91,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b1400013c' },
    title: 'contenttype title 11',
    name: 'contentype name 11',
    content: 'Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',
    dek: 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.',
    random: 62,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b1400013d' },
    title: 'contenttype title 12',
    name: 'contentype name 12',
    content: 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
    dek: 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
    random: 29,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b1400013e' },
    title: 'contenttype title 13',
    name: 'contentype name 13',
    content: 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.',
    dek: 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.',
    random: 13,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b1400013f' },
    title: 'contenttype title 14',
    name: 'contentype name 14',
    content: 'Nunc purus. Phasellus in felis. Donec semper sapien a libero.',
    dek: 'Ut tellus. Nulla ut erat id mauris vulputate elementum.',
    random: 36,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b14000140' },
    title: 'contenttype title 15',
    name: 'contentype name 15',
    content: 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.',
    dek: 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    random: 56,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b14000141' },
    title: 'contenttype title 16',
    name: 'contentype name 16',
    content: 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.',
    dek: 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
    random: 46,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b14000142' },
    title: 'contenttype title 17',
    name: 'contentype name 17',
    content: 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.',
    dek: 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.',
    random: 25,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b14000143' },
    title: 'contenttype title 18',
    name: 'contentype name 18',
    content: 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',
    dek: 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
    random: 18,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b14000144' },
    title: 'contenttype title 19',
    name: 'contentype name 19',
    content: 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.',
    dek: 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.',
    random: 66,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b14000145' },
    title: 'contenttype title 20',
    name: 'contentype name 20',
    content: 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',
    dek: 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.',
    random: 61,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b14000146' },
    title: 'contenttype title 21',
    name: 'contentype name 21',
    content: 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.',
    dek: 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.',
    random: 86,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b14000147' },
    title: 'contenttype title 22',
    name: 'contentype name 22',
    content: 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.',
    dek: 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.',
    random: 62,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b14000148' },
    title: 'contenttype title 23',
    name: 'contentype name 23',
    content: 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.',
    dek: 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.',
    random: 87,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  },
  {
    id: { '$oid': '594585ddfc13ae3b14000149' },
    title: 'contenttype title 24',
    name: 'contentype name 24',
    content: 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    dek: 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.',
    random: 47,
    author: { '$oid': '59456d2dfc13ae3b14000119' },
  }
];

module.exports = contenttypes;